# Note: 'fun' is short for 'function' (ie: the function the service should perform).
int8 FUN_SET_DIGITAL_OUT = 1
int8 FUN_SET_CONFIGURE_OUT = 2
int8 FUN_SET_TOOL_DIG_OUT = 3
int8 FUN_SET_ANALOG_OUT = 4
int8 FUN_SET_TOOL_VOLTAGE = 5

# valid values for 'state' when setting digital IO or flags
int8 STATE_OFF = 0
int8 STATE_ON = 1

# valid 'state' values when setting tool voltage
int8 STATE_TOOL_VOLTAGE_0V = 0
int8 STATE_TOOL_VOLTAGE_12V = 12
int8 STATE_TOOL_VOLTAGE_24V = 24

# valid 'analog_type' values when setting analog io
int8 ANALOG_CURRENT = 0
int8 ANALOG_VOLTAGE = 1

# request fields
int8 fun
int8 pin
int8 analog_type
float64 state
---
bool success